apiVersion: apps/v1
kind: Deployment
metadata:
  name: cluster-prune-operator
spec:
  replicas: 1
  selector:
    matchLabels:
      name: cluster-prune-operator
  template:
    metadata:
      labels:
        name: cluster-prune-operator
    spec:
      serviceAccountName: cluster-prune-operator
      containers:
        - name: cluster-prune-operator
          image: REPLACE_IMAGE
          ports:
          - containerPort: 60000
            name: metrics
          command:
          - cluster-prune-operator
          imagePullPolicy: Always
          env:
            - name: WATCH_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: OPERATOR_NAME
              value: "cluster-prune-operator"
